ViveportSoftware/pc-lib

lib/index.ts, lib/plugin/inworld-npc/configs.ts, lib/plugin/inworld-npc/desc.ts, lib/plugin/inworld-npc/index.ts, lib/plugin/inworld-npc/type.ts, lib/plugin/type.ts
Added:
- Added Inworld NPC field, including `sceneId`, `characterId`, `vrmUrl`, `greetingMessageToNpc` and `autoFollowMode`.
sub ticket: [CONNECT-1644](https://htcsense.jira.com/browse/CONNECT-1644) 
ticket: [CONNECT-1615](https://htcsense.jira.com/browse/CONNECT-1615)
=> [CONNECT-1644] feat: Added Inworld NPC plugin

lib/index.ts, lib/plugin/inworld-npc/configs.ts, lib/plugin/inworld-npc/desc.ts, lib/plugin/inworld-npc/index.ts, lib/plugin/inworld-npc/type.ts, lib/plugin/trigger-and-action/flow/configs.ts, lib/plugin/trigger-and-action/flow/desc.ts, lib/plugin/trigger-and-action/flow/index.ts, lib/plugin/trigger-and-action/flow/type.ts, lib/plugin/trigger-and-action/index.ts, lib/plugin/type.ts, package.json
- Add flow to trigger and action
- Add in world NPC
=> Release 0.0.39

lib/plugin/inworld-npc/configs.ts, lib/plugin/pick-and-throw/index.ts
Added:
- Adjusted the configs type for autoFollowMode.
- Exported the Desc and Type for pick-and-throw.
sub ticket: [CONNECT-1644](https://htcsense.jira.com/browse/CONNECT-1644)
ticket: [CONNECT-1615](https://htcsense.jira.com/browse/CONNECT-1615)
=> [CONNECT-1644] feat: Adjusted the configs type for autoFollowMode

lib/plugin/trigger-and-action/action/desc.ts, lib/plugin/trigger-and-action/action/type.ts
- add inworld npc waiting speak action type
- add inworld npc stop waiting speak action type
ticket: https://htcsense.jira.com/browse/CONNECT-1641
=> Feature/spencer yang/add inworld npc speak action

lib/plugin/trigger-and-action/action/desc.ts
- remove InworldNpcWaitingSpeak stringParams
=> feat: remove inworldNpcWaitingSpeak stringParams

.github/workflows/release-please.yml, .husky/commit-msg, .husky/pre-commit, README.md, commitlint.config.js, package.json, pnpm-lock.yaml, tsconfig.json
1. add husky pre-commit
2. add commitlint
3. add github flow for auto release
=> Feature/john cheng/improve dx flow

package.json, pnpm-lock.yaml
- Updated gts from 3.1.1 to 5.0.1.
=> fix: upgraded GTS to avoid encountering the originalKeywordKind error

lib/plugin/trigger-and-action/action/configs.ts, lib/plugin/trigger-and-action/action/desc.ts, lib/plugin/trigger-and-action/action/type.ts, lib/plugin/trigger-and-action/trigger/configs.ts
add action type:
1. EntityEnableByTag = 300014,
2. EntityDisableByTag = 300015
=> feat: add enable/disable entity by tag action type

lib/plugin/trigger-and-action/action/configs.ts, lib/plugin/trigger-and-action/trigger/configs.ts
=> feat: add tags attribute

lib/plugin/media/desc.ts
=> fix(lib/plugin/media/desc): link button text desc

lib/index.ts, lib/plugin/setting/configs.ts, lib/plugin/setting/desc.ts, lib/plugin/setting/index.ts, lib/plugin/setting/type.ts, lib/plugin/type.ts
- add setting plugin
- add occlusion culling module
=> Feature/spencer yang/add setting plugin

lib/plugin/media/configs.ts, lib/plugin/media/desc.ts
ticket https://htcsense.jira.com/browse/CONNECT-1834
add spatial sound toggle to video/audio component
=> feat: add spatial sound toggle to video/audio component

lib/plugin/media/configs.ts, lib/plugin/media/desc.ts, lib/plugin/type.ts
=> Feature/spencer yang/add audio zone taggle

lib/plugin/media/configs.ts
=> fix: audio zone config

lib/plugin/trigger-and-action/action/desc.ts, lib/plugin/trigger-and-action/action/type.ts
ticket: [CONNECT-1962](https://htcsense.jira.com/browse/CONNECT-1962)
=> feat: add new action type - teleport avatar

lib/plugin/trigger-and-action/action/desc.ts, lib/plugin/trigger-and-action/action/type.ts
ticket: https://htcsense.jira.com/browse/CONNECT-1995
=> feat: add new action - assign user asset

lib/index.ts, lib/plugin/networked/configs.ts, lib/plugin/networked/desc.ts, lib/plugin/networked/index.ts, lib/plugin/networked/type.ts, lib/plugin/type.ts
Add networked type
1. Tranform: Can sync position and rotation
2. Anim: Can sync baselayer anim state
=> feat: add networked type

lib/index.ts, lib/plugin/animate-path/configs.ts, lib/plugin/animate-path/desc.ts, lib/plugin/animate-path/index.ts, lib/plugin/animate-path/type.ts, lib/plugin/trigger-and-action/action/configs.ts, lib/plugin/trigger-and-action/action/desc.ts, lib/plugin/trigger-and-action/trigger/configs.ts, lib/plugin/type.ts
- add animate-path
- update trigger&action schema (add: inworld auto trigger)
=> feat: add animation-path & update trigger&action schema

lib/plugin/animate-path/configs.ts, lib/plugin/animate-path/desc.ts
add  cameraEntityId and animationRotation
=> feat: update animate path parameter

lib/plugin/trigger-and-action/action/configs.ts, lib/plugin/trigger-and-action/action/desc.ts, lib/plugin/trigger-and-action/trigger/configs.ts, lib/plugin/trigger-and-action/trigger/desc.ts
- add enable value to all trigger and action
=> Feature/spencer yang/connect 2497

lib/plugin/trigger-and-action/action/desc.ts, lib/plugin/trigger-and-action/trigger/desc.ts
=> feat: remove enabled check box

lib/plugin/media/desc.ts
=> modify wording

lib/plugin/media/desc.ts
=> feat: force build

lib/index.ts, lib/plugin/physic/configs.ts, lib/plugin/physic/desc.ts, lib/plugin/physic/index.ts, lib/plugin/physic/type.ts, lib/plugin/type.ts
- add physic plugin and custom rigidbody module
=> [CONNECT-2639] add physic 

lib/plugin/trigger-and-action/trigger/type.ts
=> feat: add sitInSeat trigger type

lib/plugin/trigger-and-action/action/desc.ts, lib/plugin/trigger-and-action/action/type.ts
- add TaskComplete action type
=> [CONNECT-2681]add TaskComplete action type

lib/plugin/trigger-and-action/trigger/type.ts
- add action types EnterAnyWorld and EnterMyWorld
=> [CONNECT-2703]add action types EnterAnyWorld and EnterMyWorld

lib/plugin/trigger-and-action/action/desc.ts, lib/plugin/trigger-and-action/action/type.ts
add action types EnterAnyWorld and EnterMyWorld
=> [CONNECT-2822] add EntityAssetUnload, EntityAssetReload, EntityDestroy action

lib/index.ts, lib/plugin/minimap/configs.ts, lib/plugin/minimap/desc.ts, lib/plugin/minimap/index.ts, lib/plugin/minimap/type.ts, lib/plugin/type.ts
=> Feature/ijon hsieh/research 31 minimap

lib/plugin/trigger-and-action/action/configs.ts, lib/plugin/trigger-and-action/action/desc.ts
- [add a description input to the [Action] taskComplete]
=> [CONNECT-2929]add a description input to the [Action] taskComplete

.eslintrc.json, README.md, global.d.ts, lib/enums/avatar.ts, lib/enums/index.ts, lib/index.ts, package.json, pnpm-lock.yaml, rollup.config.js, sdk/create-extensions-sdk/index.ts, sdk/create-sdk-template/index.js, sdk/create-sdk-template/interfaces/IAvatar.js, sdk/create-sdk-template/interfaces/IControlledPlayer.js, sdk/create-sdk-template/interfaces/IPlayer.js, sdk/create-sdk-template/output/bundle.js, sdk/create-sdk/index.ts, sdk/create-sdk/template.ts, tsconfig.json
**add**
1. New script for generate literal template _pnpm run build-template_
2. Use rollup bundle interface template by contacting the import js files
3. CreateSDK class for pc extension upload script 
4. Add avatar enum for create-sdk import test
**refactor**
1. Create sdk folder to put related code in the folder
=> Feature/yuni chou/create sdk interface template

sdk/create-sdk-ts/services/network/interface/INetworkService.ts
1. Fix sendMessage options docs
=> docs(create-sdk): fix sendMessage options docs

sdk/create-sdk-ts/services/player/enums/move.ts, sdk/create-sdk-ts/services/player/index.ts, sdk/create-sdk-ts/services/player/interface/ILocalPlayer.ts
=> feat(create-SDK): add local players xr & move events

sdk/create-sdk-ts/services/player/interface/IPlayer.ts, sdk/create-sdk-ts/template.ts
Modify "colliderHit" event param from `entity` to `event`.
=> feat(create-sdk): modify "colliderHit" event param

lib/plugin/trigger-and-action/action/desc.ts, lib/plugin/trigger-and-action/action/type.ts
add new action: play particle system
=> feat: [CONNECT-2451] new action: play particle system

lib/plugin/trigger-and-action/action/type.ts
Open below actions:
**Action Type**
EntityAssetUnload disable entity + unload asset
EntityAssetReload enable entity + reload asset
EntityAssetDestroy destroy entity + remove asset
=> feat: open entity resource release actions to external creator

lib/plugin/trigger-and-action/action/type.ts
feat: [CONNECT-2822] open entity resource release actions to external creator ([#250](https://github.com/ViveportSoftware/pc-lib/pull/250))
=> feat(create-SDK): merge develop  

sdk/create-sdk-ts/services/camera/CameraService.ts, sdk/create-sdk-ts/services/camera/enums/camera.ts, sdk/create-sdk-ts/services/camera/interface/ICameraService.ts
1. Rename perspective to pov
2. Add planned tag to pov feature
=> chore: rename perspective to pov (point of view)

sdk/create-sdk-ts/services/player/Avatar.ts, sdk/create-sdk-ts/services/player/Player.ts, sdk/create-sdk-ts/services/player/interface/IAvatar.ts, sdk/create-sdk-ts/services/player/interface/IPlayer.ts
=> feat: add player collision events, move collision

lib/plugin/media/configs.ts, lib/plugin/media/desc.ts
remove cast lightmap shadow for PS
=> Feature/ej huang/remove cast lightmap shadow

lib/plugin/media/desc.ts, lib/plugin/media/index.ts, lib/plugin/media/type.ts
=> Feature/ej huang/auto select quality priority

sdk/create-sdk-ts/export-sdk.ts, sdk/create-sdk-ts/index.ts, sdk/create-sdk-ts/services/quest/CheckTask.ts, sdk/create-sdk-ts/services/quest/ProgressBarTask.ts, sdk/create-sdk-ts/services/quest/Quest.ts, sdk/create-sdk-ts/services/quest/QuestService.ts, sdk/create-sdk-ts/services/quest/Task.ts, sdk/create-sdk-ts/services/quest/enums/task.ts, sdk/create-sdk-ts/services/quest/index.ts, sdk/create-sdk-ts/services/quest/interface/ICheckTask.ts, sdk/create-sdk-ts/services/quest/interface/IProgressBarTask.ts, sdk/create-sdk-ts/services/quest/interface/IQuest.ts, sdk/create-sdk-ts/services/quest/interface/IQuestService.ts, sdk/create-sdk-ts/services/quest/interface/ITask.ts
=> feat: add sdk quest service

lib/plugin/trigger-and-action/trigger/configs.ts
add task description to trigger config
=> feat: add task description to trigger config

lib/plugin/media/configs.ts, lib/plugin/media/desc.ts, lib/plugin/type.ts
- Added animation attributes to the Polygon Streaming plugin
- Modified JSON schema type to handle an array of JSON attributes in the editor extension.
=> Added animation attributes to the Polygon Streaming plugin
